import "./globals.css";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import Footer from "@/components/common/Footer";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/common/Navbar";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Indigenous Conference Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className={`${lato.className} bg-indian/70`}>
        <main>
          <Navbar />
          {children}
          <Footer />
          <Toaster position="top-right" />
        </main>
      </body>
    </html>
  );
}
